<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup Condition="'$(RuntimeIdentifier)' != ''">
		<RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
	</PropertyGroup>

</Project>
