<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup Condition="'$(RuntimeIdentifier)' != ''">
		<RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.105.1" />
		<PackageReference Include="Dapper" Version="2.1.79" />
		<PackageReference Include="QuestPDF" Version="2026.7.3" />
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
		<PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
		<PackageReference Include="Serilog.Sinks.MSSqlServer" Version="10.0.0" />
		<PackageReference Include="SkiaSharp" Version="4.151.1" />
		<PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="4.151.1" Condition="'$(RuntimeIdentifier)' == 'win-x64'" />
		<PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.151.1" Condition="'$(RuntimeIdentifier)' == 'linux-x64'" />
		<PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Domain\Domain.csproj" />
		<ProjectReference Include="..\Utilities\Utilities.csproj" />
	</ItemGroup>

</Project>
