<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup Condition="'$(RuntimeIdentifier)' != ''">
		<RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="12.1.1" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.12" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.11" />
		<PackageReference Include="QRCoder" Version="1.8.0" />
		<PackageReference Include="QuestPDF" Version="2026.7.3" />
		<PackageReference Include="SkiaSharp" Version="4.151.1" />
		<PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="4.151.1" Condition="'$(RuntimeIdentifier)' == 'win-x64'" />
		<PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.151.1" Condition="'$(RuntimeIdentifier)' == 'linux-x64'" />
		<PackageReference Include="ZXing.Net" Version="0.16.11" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Domain\Domain.csproj" />
		<ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
		<ProjectReference Include="..\Utilities\Utilities.csproj" />
	</ItemGroup>


</Project>
